name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Archive Release
        uses: nomandhoni-cs/Showwand@master
        with:
          filename: 'release.zip'
          exclusions: '*.git*'
      - name: Upload Release
        uses:  nomandhoni-cs/Showwand@v1
        with:
          artifacts: 'release.zip'
          token: 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
